services:
  united:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/home/myuser/code
      - ./db.sqlite3:/home/myuser/code/db.sqlite3
    ports:
      - "8000:8000"
    entrypoint: [ "/entrypoint.sh" ]
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]